### ISSUE TITLE
Initial roadmap

### ISSUE THREAD

**Issue by MaulingMonkey** [MaulingMonkey/jni-bindgen#1]
## Documentation
- [x] Automatically Link
- [x] Make Configurable

## Classes
- [x] Generate Rust structs
- [x] Implement Deref to super
- [x] Implement AsRef? for interfaces + super
- [ ] ~~Implement TryFrom from super, interfaces?~~ https://github.com/MaulingMonkey/jni-bindgen/issues/14
- [x] Generate wrappers for methods
- [ ] ~~Generate wrappers for fields~~ https://github.com/MaulingMonkey/jni-bindgen/issues/13

## Methods
- [x] Generate wrappers
- [x] Provide means of configuring how overload conflicts are resolved?

## Interfaces
- [x] Generate Rust structs
- [x] Implement AsRef? for interfaces
- [ ] ~~Implement TryFrom for interfaces?~~ https://github.com/MaulingMonkey/jni-bindgen/issues/14
- [x] Generate wrappers for methods

## Enums
- [x] Generate Rust structs
- [x] Implement AsRef? for interfaces + super
- [x] Generate wrappers for methods
- [ ] ~~Generate wrappers for enumeration values~~ https://github.com/MaulingMonkey/jni-bindgen/issues/13

## Exceptions
- [x] Provide a means of converting Java exceptions into Result s or panics.
- [ ] ~~Provide a means of throwing exceptions in Java~~ https://github.com/MaulingMonkey/jni-bindgen/issues/16
