### ISSUE TITLE
jni_glue::java! macro checklist

### ISSUE THREAD

**Issue by MaulingMonkey** [MaulingMonkey/jni-bindgen#55]
# Before Initial Commit

* [ ] Require `unsafe` keyboard since it's not yet 100% sound
* [ ] Add panic catcher to avoid unwinding rust panics into JNI
* [ ] Document that mismatched return types can cause soundness issues (not part of JNI sig)
* [ ] Document that mismatched argument types *shouldn't* cause soundness issues (part of JNI sig)

# Fix missing API bits

* [ ] Implement type that Rust code can convert errors into to throw Java Exceptions
* [ ] Allow unsafe keyword on fns?
* [ ] ...?

# Make API sound

* [ ] Find/parse corresponding .class info
* [ ] Verify java metadata via autogenerated tests and macro checks
* [ ] Document edge cases (custom JVM with bad symbols, mismatching .jar s, etc.)
